FROM node:latest

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install  

COPY . .

EXPOSE 5173

# Start met hot reload (bijv. met nodemon)
CMD ["npm", "run", "dev", "--","--host", "0.0.0.0"]
